INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location", "years_to_mature", "years_to_bestbefore") VALUES (1, 'Het Anker', 'Gouden Carolus Cuvee van de Keizer Imperial Dark', 'Quadrupel', 'Wikkel', 10, 5);
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location", "years_to_mature") VALUES (2, 'Hertog Jan', 'Grand Prestige', 'Quadrupel', 'Etiket, dop', 8);
INSERT INTO "library_beer" ("id", "brewery", "name", "category") VALUES (3, 'Het Anker', 'Gouden Carolus Whisky Infused', 'Quadrupel');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "years_to_bestbefore") VALUES (4, 'St.Bernardus', 'St.Bernardus Abt 12', 'Quadrupel', 4);
INSERT INTO "library_beer" ("id", "brewery", "name", "category") VALUES (5, 'Kompaan', 'The Black Gold Bloedbroeder', 'Stout + ruby port');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "years_to_bestbefore") VALUES (6, 'Rochefort', 'Rochefort 8', 'Gerstewijn', 5);
INSERT INTO "library_beer" ("id", "brewery", "name", "category") VALUES (7, 'The Musketeers', 'Troubadour Imperial stout', 'Stout');
INSERT INTO "library_beer" ("id", "brewery", "name", "category") VALUES (8, 'The Musketeers', 'Troubadour Obscura', 'Milde Stout');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "years_to_bestbefore") VALUES (9, 'De Koningshoeven', 'La Trappe Quadrupel', 'Quadrupel', 3);
INSERT INTO "library_beer" ("id", "brewery", "name", "category") VALUES (10, 'De Halve Maan', 'Straffe Hendrik Quadrupel', 'Quadrupel');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location") VALUES (11, 'De Halve Maan', 'Straffe Hendrik Heritage', 'Quadrupel', 'Etiket');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location", "years_to_mature", "years_to_bestbefore") VALUES (12, 'Maallust', 'Maallust 1818', 'Quadrupel', 'Etiket', 25, 25);
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location", "years_to_mature", "years_to_bestbefore") VALUES (13, 'Frontaal', 'Rhodesian', 'Gerstewijn', 'Etiket', 10, 5);
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location") VALUES (14, 'Abdij van Orval', 'Orval', 'Trappist', 'Etiket');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location", "years_to_mature", "years_to_bestbefore") VALUES (15, '3 Fonteinen', 'Oude Geuze', 'Geuze', 'Etiket, kurk', 15, 40);
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location", "years_to_bestbefore") VALUES (16, 'Boon', 'Oude Geuze Boon', 'Geuze', 'Wikkel', 20);
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location") VALUES (17, 'Van Steenberge', 'Gulden Draak 9000 Quadrupel', 'Quadrupel', 'Etiket');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location") VALUES (18, 'Van Steenberge', 'Gulden Draak Brewmaster Edition', 'Bruin, dubbel', 'Etiket');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "years_to_mature") VALUES (19, 'Vanhonsebrouck', 'Kasteel Donker', 'Bruin, dubbel', 15);
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "years_to_mature", "years_to_bestbefore") VALUES (20, 'Abdij van Val Dieu', 'Val-Dieu Grand Cru', 'Strong Ale', 10, 5);
INSERT INTO "library_beer" ("id", "brewery", "name", "category") VALUES (21, 'Bosteels', 'Pauwel Kwak', 'Strong Ale');
INSERT INTO "library_beer" ("id", "brewery", "name", "category", "bottle_date_location", "years_to_mature", "years_to_bestbefore") VALUES (22, 'Abdij van Chimay', 'Chimay Grande Reserve', 'Quadrupel', 'Etiket', 15, 5);


INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "purchase_price", "purpose", "comments") VALUES (1, '2019-09-30', '2018-01-01', 2, '6.50', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "purchase_price", "purpose", "comments") VALUES (1, '2020-11-27', '2019-01-01', 4, '6.50', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "purchase_price", "purpose", "comments") VALUES (1, '2021-11-26', '2021-01-01', 4, '6.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "purpose", "comments") VALUES (2, '2019-09-30', '2018-01-01', 1, 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "purpose", "comments") VALUES (2, '2019-09-30', '2019-01-01', 3, 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "purpose", "comments") VALUES (2, '2020-11-27', '2020-01-01', 4, 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "purchase_price", "purpose", "comments") VALUES (2, '2021-11-26', '2021-01-01', 4, '4.92', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (3, '2020-11-27', 4, '2024-12-12', '120162', '7.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (4, '2020-11-27', 5, '2024-06-26', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (4, '2021-11-26', 4, '2025-07-13', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (5, '2021-11-26', 8, '2024-11-27', '', '7.50', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (6, '2020-11-27', '2019-10-17', 4, '2024-10-17', '', '6.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (6, '2021-11-26', '2021-06-17', 4, '2026-06-17', '', '6.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (7, '2020-11-27',4, '2022-11-07', '', '7.50', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (8, '2021-11-26',4, '2024-05-26', '', '6.50', 'triage', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purpose", "comments") VALUES (9, '2019-09-30', '2019-11-01', 4, '2022-11-01', '', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (9, '2021-11-26', '2021-08-01', 4, '2022-11-01', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (10, '2021-11-26', 2, '2023-08-20', '', '6.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (10, '2021-11-26', 2, '2023-12-01', '', '6.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "bottle_date", "quantity", "bottle_number", "purchase_price", "purpose", "comments") VALUES (11, '2018-01-01', 1, '25973', '18.00', 'Eigen gebruik', 'Oud jaars avond?');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "bottle_number", "purchase_price", "purpose", "comments") VALUES (12, '2020-11-27', '2020-01-01', 4, '0003, 0067, 0941 0944, ', '8.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "bottle_number", "purchase_price", "purpose", "comments") VALUES (12, '2021-11-26', '2021-01-01', 4, '00412,00416,00444,00453', '8.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "bottle_number", "purchase_price", "purpose", "comments") VALUES (13, '2020-11-27', '2020-01-01', 2, '', '8.50', 'verkoop', 'Proeven! oud en nieuw');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (14, '2020-11-27', '2020-08-25', 6, '2025-08-25', '', '3.15', '', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (14, '2021-11-26', '2021-10-06', 6, '2026-10-06', '', '3.15', '', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (15, '2020-11-27', '2019-04-03', 3, '2039-10-26', '', '13.95', 'verkoop', 'assemblage nr 63, seizoen 18/19');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (16, '2020-11-27', '2018-01-01', 3, '2040-08-26', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (17, '2020-11-27', '2019-01-01', 4, '2023-03-03', 'brewtank no1', '7.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (17, '2021-11-26', '2020-01-01', 4, '2024-03-15', '', '7.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (18, '2020-11-27', '2019-01-01', 4, '2023-08-12', '', '8.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (19, '2020-01-01', 4, '2025-08-25', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (19, '2021-11-26', 4, '2025-11-24', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (20, '2019-01-01', '2019-01-01', 2, '2021-01-07', '', '6.60', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (20, '2020-11-27', '2020-11-27', 4, '2022-05-08', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (20, '2021-11-26', '2021-11-26', 4, '2023-05-28', '', '5.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "quantity", "best_before_date", "bottle_number", "purpose", "comments") VALUES (21, 2, '2022-02-24', '', 'verkoop', 'proeven!');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (22, '2019-09-30', '2019-01-01', 4, '2019-03-01', '', '6.00', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "best_before_date", "bottle_number", "purchase_price", "purpose", "comments") VALUES (22, '2020-11-27', '2020-01-01', 8, '2025-04-01', '', '10.95', 'verkoop', '');
INSERT INTO "stock_beer" ("librarybeer_id", "purchase_date", "bottle_date", "quantity", "bottle_number", "purchase_price", "purpose", "comments") VALUES (22, '2021-11-26', '2021-01-01', 4, '', '5.49', 'verkoop', '');
